Task 9: Allow users to select categories and filter reviews based on the chosen category.
RoKen1000/nc-games pull request #7
Opened 2023-04-20 15:01 UTC by RoKen1000

Task 9: Allow users to select categories and filter reviews based on the chosen category.

2023-04-20 15:15 UTC, B7Bprog requested changes
Hey Ross, instead of filtering the reviews here, please let your API do that.  See my comments for where and how to do that. 

Once it's done, please send another PR with the finished code.

2023-04-20 15:15 UTC, B7Bprog commented on src/components/ReviewContainer.jsx
> +    const filteredReviews = reviews.filter((review) => {
Instead of filtering the reviews here at the front end, please make use of your API as it should have an endpoint that accepts queries.

2023-04-20 15:15 UTC, B7Bprog commented on src/api.js
> +    })
Here in this file you can reuse the function that fetches all the reviews, but add 'axios params' to that request. For this see NC Notes: Axios/Axios Params.

2023-04-21 08:49 UTC, callumu21 approved these changes
Nice job implementing those changes, Ross. This should be good to merge now 👍

2023-04-21 08:49 UTC, merged